

-- QUAL PRODUTO	TEVE MAIOR QUANTIDADE DE VENDAS NO MES 7 DE 1996

SELECT TOP 1 * FROM TB_PRODUTO

SELECT TOP 1* FROM TB_DETALHE_PEDIDO

SELECT TOP 1 * FROM TB_PEDIDO

SELECT TOP 1 A.ProdutoId, A.Descricao, SUM(Quantidade) AS MaiorVenda  FROM TB_PRODUTO A
INNER JOIN TB_DETALHE_PEDIDO B
ON A.ProdutoId = B.ProdutoId
INNER JOIN TB_PEDIDO C
ON B.NumeroPedido = C.NumeroPedido
WHERE DataPedido BETWEEN '1996-07-01' AND '1996-07-31'
GROUP BY A.ProdutoId, A.Descricao
ORDER BY MaiorVenda DESC

-- QUAL CLIENTE TEVE O MAIOR GASTO NO MÊS 7 DE 1996

SELECT TOP 1 NomeCompleto, SUM(D.Preco) [TOTAL GASTOS]  FROM TB_CLIENTE C
INNER JOIN TB_PEDIDO P ON C.ClienteId = P.ClienteId
INNER JOIN TB_DETALHE_PEDIDO D ON D.NumeroPedido = P.NumeroPedido
WHERE P.DataPedido BETWEEN '1996-07-01' AND '1996-07-31'
GROUP BY NomeCompleto
ORDER BY 2 DESC

