

-- LISTA TODOS CLIENTES QUE MORAM NA ALEMANHA

SELECT C.*, E.Pais FROM TB_CLIENTE C
INNER JOIN TB_ENDERECO E ON C.ClienteId = E.ClienteId
WHERE E.Pais = 'Alemanha'


-- LISTA TODOS CLIENTES QUE COMPRARAM PRODUTOS DA CATEGORIA BEBIDA

SELECT TOP 1 * FROM TB_PEDIDO
SELECT TOP 1 * FROM TB_DETALHE_PEDIDO
SELECT TOP 1 * FROM TB_PRODUTO 
SELECT TOP 1 * FROM TB_CATEGORIA 


SELECT C.NomeCompleto FROM TB_CLIENTE C
INNER JOIN TB_PEDIDO P ON C.ClienteId = P.ClienteId
INNER JOIN TB_DETALHE_PEDIDO D ON D.NumeroPedido = P.NumeroPedido
INNER JOIN TB_PRODUTO PR ON PR.ProdutoId = D.ProdutoId
INNER JOIN TB_CATEGORIA CAT ON CAT.CategoriaId = PR.CategoriaId
WHERE CAT.CategoriaId = 1
GROUP BY C.NomeCompleto