 CREATE TABLE TB_CLIENTE 
 (
	ID INT IDENTITY(1, 1),
	NOME VARCHAR(70),
	CPF VARCHAR(11),
	DATA_NASCIMENTO DATETIME2,
	EMAIL VARCHAR(70),
	CONSTRAINT PK_CLIENTE PRIMARY KEY(ID)
 );

 INSERT INTO TB_CLIENTE
 (NOME, CPF, DATA_NASCIMENTO, EMAIL)
 VALUES
 ('Manoel Alcântara', '22222222200', '1987-06-12 16:18:22', 'manoelalcantara@email.com');

 SELECT * FROM TB_CLIENTE

