CREATE TABLE TB_PRODUTO
(
	ProdutoId INT IDENTITY(1001, 1) NOT NULL,
	NumContrato INT NOT NULL,

	CONSTRAINT PK_PRODUTO PRIMARY KEY (ProdutoId, NumContrato)

)

-- ALTER TABLE TB_PRODUTO
-- ADD CONSTRAINT PK_PRODUTO PRIMARY KEY (ProdutoId);

CREATE TABLE TB_CLIENTE
(
	CPF VARCHAR(12) NOT NULL,
	CONSTRAINT UQ_CLIENTE_CPF(CPF)
)

-- ALTER TABLE TB_CLIENTE
-- ADD CONSTRAINT UQ_CLIENTE_CPF UNIQUE(CPF);