SELECT * FROM TB_CLIENTE_SP

ALTER TABLE TB_CLIENTE_SP
ADD DATA_CRIACAO DATETIME2 DEFAULT GETDATE()

UPDATE TOP(1) TB_CLIENTE_SP SET DATA_CRIACAO = '2005-02-15 15:45:36'

DELETE TOP(2) FROM TB_CLIENTE_SP